# Generated by Django 4.2.6 on 2023-10-14 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фото')),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Стaтьи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фото')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scat', to='recipe.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Post_recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aвтор статьи')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url site')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_recipes', to='recipe.post')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='scat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_post', to='recipe.subcategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tag_post', to='recipe.tag'),
        ),
    ]
