# Generated by Django 4.2.6 on 2023-10-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_post_recipes_date_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scat',
        ),
        migrations.AddField(
            model_name='post',
            name='categ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_post', to='recipe.category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
